site_name: eln2.org
nav:
  - Home: index.md
  - Eln2 Progress: progress.md
  - Electrical Age Website: https://electrical-age.net
  - Electrical Age Wiki: https://wiki.electrical-age.net
theme: material
